Ext.define('guanli.model.User', {
    extend: 'Ext.data.Model',
    xtype: "User",
    fields: [
        {name: "id", type: "number"},
        {name: "username", type: "string"},
        {name: "password", type: "string"},
        {name: "user_Manager", type: "number"},
        {name: "vip_baseinfo_create", type: "number"},
        {name: "vip_baseinfo_read", type: "number"},
        {name: "vip_baseinfo_update", type: "number"},
        {name: "vip_baseinfo_delete", type: "number"},
        {name: "vip_ZhuYuanJiLu_create", type: "number"},
        {name: "vip_ZhuYuanJiLu_read", type: "number"},
        {name: "vip_ZhuYuanJiLu_update", type: "number"},
        {name: "vip_ZhuYuanJiLu_delete", type: "number"},
        {name: "vip_ZengSongBaoXian_create", type: "number"},
        {name: "vip_ZengSongBaoXian_read", type: "number"},
        {name: "vip_ZengSongBaoXian_update", type: "number"},
        {name: "vip_ZengSongBaoXian_delete", type: "number"},
        {name: "vip_TiJianBaoGao_create", type: "number"},
        {name: "vip_TiJianBaoGao_read", type: "number"},
        {name: "vip_TiJianBaoGao_update", type: "number"},
        {name: "vip_TiJianBaoGao_delete", type: "number"},
        {name: "vip_QiTaShiXiang_create", type: "number"},
        {name: "vip_QiTaShiXiang_read", type: "number"},
        {name: "vip_QiTaShiXiang_update", type: "number"},
        {name: "vip_QiTaShiXiang_delete", type: "number"},
        {name: "vip_JiaoFeiJiLu_create", type: "number"},
        {name: "vip_JiaoFeiJiLu_read", type: "number"},
        {name: "vip_JiaoFeiJiLu_update", type: "number"},
        {name: "vip_JiaoFeiJiLu_delete", type: "number"},
        {name: "vip_BaoXianJiLu_create", type: "number"},
        {name: "vip_BaoXianJiLu_read", type: "number"},
        {name: "vip_BaoXianJiLu_update", type: "number"},
        {name: "vip_BaoXianJiLu_delete", type: "number"}
    ]
});

